version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.27
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-204-41-109.compute-1.amazonaws.com
            port: '5432'
            database: d7ennuip3dsrdn
            ssl: true
            user: futzxgztnycutb
            password: 0ddd0df298dbad63db93d6863cb5d125b92dc2f015cc376f826b75335bdfb7b4
            migrations: true
